### ISSUE TITLE
Limit of 76 poverty lines per povcalnet_cl request in R?

### ISSUE THREAD

**Issue by morkor** [worldbank/povcalnetR#17]
For example this works: 
povcalnet_cl(rep("CHN",76),seq(0.01,0.76,0.01),rep(2010,76))
while this:
povcalnet_cl(rep("CHN",77),seq(0.01,0.77,0.01),rep(2010,77))
produces an error:
"Error: assert_that: assertion must return a logical value"
[using a fully updated R version 3.6.1 (2019-07-05) on Ubuntu 18.04.3 LTS]

**Comment by tonyfujs** [comment]
Hi @morkor 
Thanks for reporting this! This is not an issue with the R package, but with the underlying Povcalnet API. For security reasons, queries that are too long are being blocked. I will check with our ITS team to see if this behavior can be modified.
