### ISSUE TITLE
povcalnet_wb() reports data apparently unavailable in web interface.

### ISSUE THREAD

**Issue by ryancbriggs** [worldbank/povcalnetR#29]
The following lines of code will report a row with data for region SAS in 2015 but NAs for 2018.

```
library(povcalnetR)
regions <- povcalnet_wb()
regions <- regions[regions$regioncode == "SAS",]
regions[regions$year == 2015,]
regions[regions$year == 2018,]
```

The [PovcalNet web interface](http://iresearch.worldbank.org/PovcalNet/povDuplicateWB.aspx), however, suppresses the results for both years as coverage in 2015 and 2018 in SAS is too low.

This inconsistency seems weird.

Ryan

**Comment by tonyfujs** [comment]
Thanks for your patience, and for reporting this @ryancbriggs 

This is a known issue, and will be addressed in an upcoming release of `PovcalNet`. 

Closing this issue as the problem comes from the underlying `PovcalNet` API, not from the `povcalnetR` package.
